INSERT INTO board.article (article_title, article_content, article_writer, created_at, updated_at)
VALUES ('vel pede blandit congue. In',
        'eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit', 'Vincent Gardner',
        'May 12, 2024', 'Oct 10, 2023'),
       ('ac mattis velit justo nec',
        'dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec,', 'Lisandra Mckenzie',
        'Apr 29, 2024', 'Feb 3, 2024'),
       ('mi. Duis risus odio, auctor',
        'ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit',
        'Clinton Macias', 'Sep 29, 2024', 'Feb 24, 2024'),
       ('luctus felis purus ac tellus.',
        'eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum',
        'Noble Jackson', 'Feb 17, 2023', 'Oct 3, 2024'),
       ('Nunc ut erat. Sed nunc', 'vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce',
        'Reuben Singleton', 'Jul 17, 2024', 'Dec 4, 2022'),
       ('Ut tincidunt orci quis lectus.',
        'non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit', 'Galena Lamb',
        'Aug 29, 2023', 'Jan 19, 2024'),
       ('tempus scelerisque, lorem ipsum sodales',
        'Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc', 'Kennan Maldonado',
        'Jul 10, 2024', 'Sep 5, 2024'),
       ('semper pretium neque. Morbi quis',
        'Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,',
        'Lysandra Chen', 'Mar 25, 2023', 'Dec 12, 2022'),
       ('tellus eu augue porttitor interdum.',
        'pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna.',
        'Eleanor Meadows', 'Oct 8, 2024', 'Jun 12, 2023'),
       ('Suspendisse sed dolor. Fusce mi',
        'netus et malesuada fames ac turpis egestas. Fusce aliquet magna', 'Julian Avila',
        'Feb 11, 2024', 'Oct 14, 2024');
INSERT INTO board.article (article_title, article_content, article_writer, created_at, updated_at)
VALUES ('placerat velit. Quisque varius. Nam',
        'felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.',
        'Brody Hebert', 'Mar 29, 2023', 'Nov 12, 2024'),
       ('nec, cursus a, enim. Suspendisse',
        'Sed id risus quis diam luctus lobortis. Class aptent taciti', 'Lacy Larson',
        'May 17, 2023', 'Jul 19, 2024'),
       ('eu dolor egestas rhoncus. Proin',
        'Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer', 'Caleb Steele',
        'Oct 6, 2024', 'Sep 13, 2023'),
       ('magna, malesuada vel, convallis in,',
        'sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,', 'Addison Rhodes',
        'Sep 2, 2024', 'Dec 10, 2022'),
       ('eget, volutpat ornare, facilisis eget,',
        'velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod', 'Renee Boyd',
        'Apr 12, 2023', 'Jun 20, 2023'),
       ('velit. Aliquam nisl. Nulla eu',
        'nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat', 'Omar Osborn',
        'Jun 11, 2023', 'Aug 10, 2023'),
       ('ligula. Donec luctus aliquet odio.',
        'dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus', 'Randall Stephenson',
        'Jun 30, 2023', 'Mar 28, 2023'),
       ('Nulla tincidunt, neque vitae semper',
        'aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae', 'Wynter Dawson',
        'Aug 12, 2024', 'Jan 29, 2024'),
       ('molestie sodales. Mauris blandit enim',
        'dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et', 'Palmer Sharp',
        'Sep 25, 2024', 'Jun 13, 2023'),
       ('rutrum. Fusce dolor quam, elementum',
        'ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam', 'Renee Kirby',
        'Mar 9, 2023', 'Aug 7, 2023');
INSERT INTO board.article (article_title, article_content, article_writer, created_at, updated_at)
VALUES ('ac urna. Ut tincidunt vehicula',
        'magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna.', 'Herman Bean',
        'Jul 4, 2024', 'Apr 8, 2024'),
       ('nec ante blandit viverra. Donec',
        'fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque',
        'Charissa Aguirre', 'May 8, 2024', 'Dec 6, 2022'),
       ('purus mauris a nunc. In',
        'felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.',
        'Cheryl Snider', 'Jan 13, 2023', 'Jun 5, 2023'),
       ('dolor. Fusce mi lorem, vehicula',
        'molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis.', 'Dante Sykes',
        'Jul 18, 2024', 'Oct 20, 2023'),
       ('Integer sem elit, pharetra ut,',
        'condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus', 'Vanna Oneil',
        'Sep 5, 2023', 'Jan 22, 2024'),
       ('arcu. Aliquam ultrices iaculis odio.',
        'amet ornare lectus justo eu arcu. Morbi sit amet massa.', 'Aphrodite Bell', 'Jan 11, 2024',
        'Sep 24, 2024'),
       ('auctor odio a purus. Duis', 'in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit',
        'Cynthia Mack', 'Aug 29, 2024', 'Feb 7, 2024'),
       ('gravida nunc sed pede. Cum',
        'semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim',
        'Hakeem Tyler', 'Oct 11, 2024', 'Apr 11, 2023'),
       ('tristique senectus et netus et',
        'egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem',
        'Victoria Bradley', 'Feb 6, 2023', 'Mar 6, 2024'),
       ('Pellentesque ut ipsum ac mi',
        'erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.',
        'Neville Lynch', 'Jan 26, 2023', 'Dec 10, 2022');
INSERT INTO board.article (article_title, article_content, article_writer, created_at, updated_at)
VALUES ('elit erat vitae risus. Duis', 'ante dictum mi, ac mattis velit justo nec ante. Maecenas',
        'Ian Stevenson', 'Feb 14, 2024', 'Sep 26, 2024'),
       ('ornare, facilisis eget, ipsum. Donec',
        'Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.',
        'Thane Romero', 'Jun 4, 2024', 'May 11, 2024'),
       ('tellus faucibus leo, in lobortis',
        'odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus.',
        'Harlan Gilmore', 'Jan 21, 2023', 'Aug 7, 2024'),
       ('tortor nibh sit amet orci.',
        'sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo',
        'Isabelle Mayer', 'Aug 11, 2024', 'Oct 27, 2024'),
       ('sem elit, pharetra ut, pharetra',
        'tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet,', 'Hannah Cervantes',
        'Mar 4, 2024', 'Dec 2, 2023'),
       ('Aliquam erat volutpat. Nulla facilisis.',
        'urna, nec luctus felis purus ac tellus. Suspendisse sed dolor.', 'Shafira Ward',
        'Dec 25, 2023', 'Jan 8, 2024'),
       ('Maecenas malesuada fringilla est. Mauris',
        'gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.', 'Cathleen Black',
        'Aug 29, 2024', 'Mar 14, 2024'),
       ('Nulla aliquet. Proin velit. Sed',
        'nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce', 'Ferdinand Lee',
        'Jul 28, 2024', 'Apr 16, 2023'),
       ('pede, malesuada vel, venenatis vel,',
        'magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna.', 'Hanae Graves',
        'Dec 5, 2022', 'Jan 29, 2024'),
       ('ipsum dolor sit amet, consectetuer',
        'nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque', 'Hiroko Frazier',
        'Aug 25, 2023', 'Sep 8, 2024');
INSERT INTO board.article (article_title, article_content, article_writer, created_at, updated_at)
VALUES ('placerat velit. Quisque varius. Nam',
        'ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat', 'Amery Ochoa',
        'May 24, 2024', 'Sep 13, 2024'),
       ('semper erat, in consectetuer ipsum',
        'pede sagittis augue, eu tempor erat neque non quam. Pellentesque', 'Basil Douglas',
        'Jan 11, 2024', 'Aug 7, 2023'),
       ('in faucibus orci luctus et',
        'dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate', 'Brynne Burnett',
        'Oct 26, 2023', 'Mar 4, 2023'),
       ('aliquet molestie tellus. Aenean egestas',
        'ornare sagittis felis. Donec tempor, est ac mattis semper, dui', 'Josephine Saunders',
        'Jan 13, 2024', 'Nov 28, 2022'),
       ('orci lacus vestibulum lorem, sit',
        'tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque', 'Evan Salazar',
        'Nov 13, 2023', 'Dec 23, 2023'),
       ('interdum ligula eu enim. Etiam',
        'odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa.', 'Tyler Pearson',
        'Jan 18, 2023', 'Sep 30, 2023'),
       ('ac facilisis facilisis, magna tellus',
        'eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris', 'Bryar Chapman',
        'Apr 22, 2023', 'Jun 29, 2024'),
       ('sit amet lorem semper auctor.',
        'ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris', 'Yvonne Herman',
        'Jul 7, 2024', 'Sep 18, 2023'),
       ('ullamcorper. Duis cursus, diam at',
        'ornare, lectus ante dictum mi, ac mattis velit justo nec', 'Alana Winters', 'Oct 21, 2023',
        'Apr 23, 2024'),
       ('eu enim. Etiam imperdiet dictum',
        'at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare', 'Kareem Mathews',
        'Jan 1, 2024', 'Jul 14, 2024');